export enum Languages {
    EN = "en",
    KH = "kh",
}
  
export const TRANSLATIONS = {
    [Languages.EN]: {
        dashboard: "Dashboard",
        users: "Staff List",
        visitors: "Visitor List",
        vehicles: "Vehicle",
        scan: "Gate Pass",
        pass: "My Pass",
        username: "Username",
        email: "Email",
        contact: "Contact",
        role: "Role",
        id: "ID",
        purpose: "Purpose",
        entry_time: "Entry time",
        exit_time: "Exit time",
        approver: "Approver",
        status: "Status",
        reject: "Reject",
        approve: "Approve",
        pending: "Pending",
        fullName: "Full Name",
        all: "All",
        filterStatus: "Filter status",
        vehicleCode: "Vehicle Code",
        model: "Model",
        type: "Type",
        driver: "Driver",
        capacity: "Capacity",
        image: "Image",
        date: "Date",
        previous: "Previous",
        next: "Next",
        vehicleDetail: "Vehicle Detail",
        vehicleUpdate: "Vehicle Update",
        visitorDetail: "Visitor Detail",
        visitorUpdate: "Visitor Update",
        password: "Password",
        login: "Login",
        logout: "Logout",
        myProfile: "My Profile",
        accountSetting: "Account Setting",
        register: "Register",
        resetForm: "Reset from"
    },
    [Languages.KH]: {
        dashboard: "ផ្ទាំងគ្រប់គ្រង",
        users: "បញ្ជីបុគ្គលិក",
        visitors: "បញ្ជីភ្ញៀវ",
        vehicles: "យានជំនិះ",
        scan: "ច្រកចេញចូល",
        pass: "លិខិតរបស់ខ្ញុំ",
        username: "នាមឈ្មោះ",
        email: "អ៊ីមែល",
        contact: "លេខទូរស័ព្ទ",
        role: "តួនាទី",
        id: "លរ",
        purpose: "គោលបំណង",
        entry_time: "ម៉ោងចូល",
        exit_time: "ម៉ោងចេញ",
        approver: "អ្នកទទួល",
        status: "ស្ថានភាព",
        reject: "បដិសេធ",
        approve: "យល់ព្រម",
        pending: "កំពុងរងចាំ",
        fullName: "ឈ្មោះពេញ",
        all: "ទាំងអស់",
        filterStatus: "តម្រងស្ថានភាព",
        vehicleCode: "កូដយានជំនិះ",
        model: "ម៉ាក",
        type: "ប្រភេទ",
        driver: "អ្នកបើកបរ",
        capacity: "ទំហំផ្ទុក",
        image: "រូបភាព",
        date: "កាលបរិច្ឆេទ",
        previous: "ថយក្រោយ",
        next: "បន្ទាប់",
        vehicleDetail: "ព័ត៍មានយានយន្ត",
        vehicleUpdate: "បច្ចុប្បន្នភាពយានយន្ត",
        visitorDetail: "ព័ត៍មានភ្ញៀវ",
        visitorUpdate: "បច្ចុប្បន្នភាពភ្ញៀវ",
        password: "លេខសំងាត់",
        login: "ចូលប្រព័ន្ធ",
        logout: "ចាកចេញ",
        myProfile: "ទំព័ររបស់អ្នក",
        accountSetting: "ការកំណត់គណនី",
        register: "ចុះឈ្មោះ",
        resetForm: "បំពេញឡើងវិញ"
    },
};